// 存储用户token
const CHANGE_USER_TOKEN = "CHANGE_USER_TOKEN"
// 设置用户资料数据
const CHANGE_USER_INFO = "CHANGE_USER_INFO"
// 清除用户token
const CLEAR_USER_TOKEN = "CLEAR_USER_TOKEN"

export { CHANGE_USER_TOKEN, CHANGE_USER_INFO, CLEAR_USER_TOKEN }
